Scripts needed to create a SLAX module by using -l option. Normal use unchanged.
git-svn-id: svn://svn.code.sf.net/p/openfoam-extend/svn/trunk/Core/OpenFOAM-1.5-dev@1510 e4e07f05-0c2f-0410-a05a-b8ba57e0c909

diff --git a/bin/foamPackBin b/bin/foamPackBin
--- a/bin/foamPackBin
+++ b/bin/foamPackBin
@@ -30,29 +30,59 @@
 #     Packs and compresses binary version of OpenFOAM for release
 #
 #------------------------------------------------------------------------------
+tmpDir=${TMPDIR:-/tmp}/foamPackDir.$$
 
-if [ $# = 0 ]
-then
-   echo "Error: architecture type expected, exiting"
-   echo
-   echo "Usage : ${0##*/} <arch> [outputDir]"
-   echo
-   exit 1
-fi
-arch=$1
+#
+# FUNCTIONS
+#
+printUsage () {
+cat <<EOF
+   Usage : ${0##*/} [-l] <arch> [outputDir]"
+EOF
+}
 
 timeStamp=$(date +%Y-%m-%d)
 packDir=$WM_PROJECT-$WM_PROJECT_VERSION
 packFile=${packDir}.${arch}_${timeStamp}.tgz
 
+#
+# OPTIONS
+#
+OPTS=`getopt hl $*`
+if [ $? -ne 0 ] ; then
+    echo "Aborting due to invalid option"
+    printUsage
+    exit 1
+fi
+
+eval set -- '$OPTS'
+while [ "$1" != "--" ]; do
+    case $1 in
+        -l) LZM=1;;
+        -h) printUsage; exit 1;;
+    esac
+    shift
+done
+shift
+
+if [ $# = 0 ]; then
+   printUsage;
+   exit 1
+fi
+arch=$1
+
+if [ $LZM ]; then
+   packFile=${packDir}.${arch}_${timeStamp}.lzm
+else
+   packFile=${packDir}.${arch}_${timeStamp}.tgz
+fi
+
 # add optional output directory
-if [ -d "$2" ]
-then
+if [ -d "$2" ]; then
    packFile="$2/$packFile"
 fi
 
-if [ -f $packFile ]
-then
+if [ -f $packFile ]; then
    echo "Error: $packFile already exists"
    exit 1
 fi
@@ -60,8 +90,7 @@ fi
 # check for essential directories
 for dir in $packDir $packDir/lib/$arch $packDir/applications/bin/$arch
 do
-   if [ ! -d $dir ]
-   then
+   if [ ! -d $dir ]; then
       echo "Error: directory $dir does not exist"
       exit 1
    fi
@@ -83,7 +112,24 @@ echo
 echo "Packing $arch port of $packDir into $packFile"
 echo
 
-tar czpf $packFile $dirList
+if [ $LZM ]; then
+
+   # Clean up on termination and on Ctrl-C
+   trap 'rm -rf $tmpDir 2>/dev/null; exit 0' EXIT TERM INT
+
+   mkdir $tmpDir $tmpDir/OpenFOAM
+   cp -arl --parents $dirList $tmpDir/OpenFOAM
+   find $tmpDir -name .svn | xargs rm -rf
+
+   chmod -R a+rX $tmpDir/OpenFOAM
+   foamDir2lzm $tmpDir $packFile
+   echo; echo
+
+else
+
+   tar --exclude-vcs czpf $packFile $dirList
+
+fi
 
 if [ $? = 0 ]
 then
diff --git a/bin/foamPackGeneral b/bin/foamPackGeneral
--- a/bin/foamPackGeneral
+++ b/bin/foamPackGeneral
@@ -31,24 +31,48 @@
 #
 #------------------------------------------------------------------------------
 
+#
+# FUNCTIONS
+#
+printUsage () {
+cat <<EOF
+   Usage : ${0##*/} " [-l] [outputDir]
+
+   Packs and compresses the OpenFOAM directory for release
+EOF
+}
+
 timeStamp=$(date +%Y-%m-%d)
 packDir=$WM_PROJECT-$WM_PROJECT_VERSION
 packFile=${packDir}.General_${timeStamp}.tgz
+LZMOPT=""
 
-if [ ! -d $packDir ]
-then
-   echo "Error: directory $packDir does not exist"
-   exit 1
+#
+# OPTIONS
+#
+OPTS=`getopt hl $*`
+if [ $? -ne 0 ] ; then
+    echo "Error: Aborting due to invalid option"
+    printUsage;
+    exit 1
 fi
 
+eval set -- '$OPTS'
+while [ "$1" != "--" ]; do
+    case $1 in
+        -l) LZMOPT="-l"; packFile=${packDir}.General_${timeStamp}.lzm;;
+        -h) printUsage; exit 1;;
+    esac
+    shift
+done
+shift
+
 # add optional output directory
-if [ -d "$1" ]
-then
+if [ -d "$1" ]; then
    packFile="$1/$packFile"
 fi
 
-if [ -f $packFile ]
-then
+if [ -f $packFile ]; then
    echo "Error: $packFile already exists"
    exit 1
 fi
@@ -65,6 +89,6 @@ echo
 echo "Packing $packDir into $packFile"
 echo
 
-foamPackSource $packDir $packFile
+foamPackSource $LZMOPT $packDir $packFile
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackSource b/bin/foamPackSource
--- a/bin/foamPackSource
+++ b/bin/foamPackSource
@@ -32,13 +32,41 @@
 #
 #------------------------------------------------------------------------------
 tmpFile=${TMPDIR:-/tmp}/foamPackFiles.$$
+tmpDir=${TMPDIR:-/tmp}/foamPackDir.$$
+
+#
+# FUNCTIONS
+#
+printUsage () {
+cat <<EOF
+   Usage : ${0##*/} directory tarFile
+
+   Packs all .C and .H files and Make/options and Make/files into <tarFile>
+EOF
+}
+
+#
+# OPTIONS
+#
+OPTS=`getopt hl $*`
+if [ $? -ne 0 ] ; then
+    echo "Error: Aborting due to invalid option"
+    printUsage;
+    exit 1
+fi
+
+eval set -- '$OPTS'
+while [ "$1" != "--" ]; do
+    case $1 in
+        -l) LZM=1;;
+        -h) printUsage; exit 1;;
+    esac
+    shift
+done
+shift
 
 if [ $# -ne 2 ]; then
-   echo "Usage : ${0##*/} directory tarFile"
-   echo ""
-   echo "Packs all .C and .H files and Make/options and Make/files into"
-   echo "<tarFile>"
-   echo ""
+   printUsage;
    exit 1
 fi
 
@@ -83,12 +111,28 @@ find -H $packDir               \
  -e '\@/t/@d'                  \
  -e '\@/Make[.A-Za-z]*/[^/]*/@d'\
  -e '\@/platforms/@d'          \
+ -e '\@/.svn/@d'               \
  > $tmpFile
 
-tar czpf $packFile --files-from $tmpFile
+if [ $LZM ]; then
 
-if [ $? = 0 ]
-then
+   # Clean up on termination and on Ctrl-C
+   trap 'rm -f $tmpFile 2>/dev/null; rm -rf $tmpDir 2>/dev/null; exit 0' EXIT TERM INT
+
+   mkdir $tmpDir $tmpDir/OpenFOAM
+   xargs -i -a $tmpFile cp -al --parents {} $tmpDir/OpenFOAM
+
+   chmod -R a+rX $tmpDir/OpenFOAM
+   foamDir2lzm $tmpDir $packFile
+   echo; echo
+
+else
+
+   tar czpf $packFile --files-from $tmpFile
+
+fi
+
+if [ $? = 0 ]; then
    echo "Finished packing and compressing $packDir into file $packFile"
 else
    echo "Error: failure packing $packDir into file $packFile"
diff --git a/bin/foamPackThirdPartyBin b/bin/foamPackThirdPartyBin
--- a/bin/foamPackThirdPartyBin
+++ b/bin/foamPackThirdPartyBin
@@ -30,13 +30,43 @@
 #     Packs and compresses binary version of OpenFOAM ThirdParty for release
 #
 #------------------------------------------------------------------------------
+tmpDir=${TMPDIR:-/tmp}/foamPackDir.$$
 
-if [ $# = 0 ]
-then
-   echo "Error: archOptionsitecture type expected, exiting"
-   echo
-   echo "Usage : ${0##*/} <archOptions> [outputDir]"
-   echo
+#
+# FUNCTIONS
+#
+printUsage () {
+cat <<EOF
+   Usage : ${0##*/} [-l] <archOptions> [outputDir]"
+EOF
+}
+
+timeStamp=$(date +%Y-%m-%d)
+packDir=$WM_PROJECT-$WM_PROJECT_VERSION
+packFile=${packDir}.${arch}_${timeStamp}.tgz
+
+#
+# OPTIONS
+#
+OPTS=`getopt hl $*`
+if [ $? -ne 0 ] ; then
+    echo "Aborting due to invalid option"
+    printUsage
+    exit 1
+fi
+
+eval set -- '$OPTS'
+while [ "$1" != "--" ]; do
+    case $1 in
+        -l) LZM=1;;
+        -h) printUsage; exit 1;;
+    esac
+    shift
+done
+shift
+
+if [ $# = 0 ]; then
+   printUsage;
    exit 1
 fi
 archOptions=$1
@@ -49,7 +79,12 @@ echo "arch3264=$arch3264"
 
 timeStamp=$(date +%Y-%m-%d)
 packDir=ThirdParty
-packFile=${packDir}.${archOptions}_${timeStamp}.tgz
+
+if [ $LZM ]; then
+   packFile=${packDir}.${arch}_${timeStamp}.lzm
+else
+   packFile=${packDir}.${arch}_${timeStamp}.tgz
+fi
 
 # add optional output directory
 if [ -d "$2" ]
@@ -69,7 +104,21 @@ echo
 echo "Packing $archOptions port of $packDir into $packFile"
 echo
 
-tar czpf $packFile $dirList
+if [ $LZM ]; then
+
+   # Clean up on termination and on Ctrl-C
+   trap 'rm -rf $tmpDir 2>/dev/null; exit 0' EXIT TERM INT
+
+   mkdir $tmpDir $tmpDir/OpenFOAM
+   cp -arl --parents $dirList $tmpDir/OpenFOAM
+   foamDir2lzm $tmpDir $packFile
+   echo; echo
+
+else
+
+   tar czpf $packFile $dirList
+
+fi
 
 if [ $? = 0 ]
 then
