Initial SVN check-in OpenFOAM-1.5-dev
git-svn-id: svn://svn.code.sf.net/p/openfoam-extend/svn/trunk/Core/OpenFOAM-1.5-dev@921 e4e07f05-0c2f-0410-a05a-b8ba57e0c909

diff --git a/bin/foamJob b/bin/foamJob
--- a/bin/foamJob
+++ b/bin/foamJob
@@ -27,67 +27,67 @@
 #     foamJob
 #
 # Description
-#     
+#
 #------------------------------------------------------------------------------
+Script=${0##*/}
 
-EXENAME=`basename $0`
+usage() {
+   while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+   cat<<USAGE
 
-printUsage () {
-cat <<EOF
-Usage: $0 [options] <application> <root> <case>
-    Runs a FOAM job in background.
-    Redirects the output to <root>/<case>/log
+usage: $Script [OPTION] <application> ...
 
-Options:
-   [-s] also sends output to screen
-   [-p] performs a parallel run of processors
-EOF
+options:
+  -case dir     specify case directory
+  -s            also sends output to screen
+  -p            parallel run of processors
+  -v ver        specify OpenFOAM version
+  -help         this usage
+
+* run an OpenFOAM job in background.
+  Redirects the output to 'log' in the case directory
+
+USAGE
+   exit 1
 }
 
+unset version
+
+# replacement for possibly buggy 'which'
 findExec() {
-    if [ "`echo $2 | grep /`" ] ; then
-        if [ -x "$2" ] ; then
-            return 0
-        fi
-    fi
-    oldIFS=$IFS
-    IFS=':'
-    for d in $1
-    do
-        #echo "testing: $d/$2" 1>&2
-        if [ -x "$d/$2" -a ! -d "$d/$2" ]; then
-            #echo "Found exec: $d/$2" 1>&2
-            IFS=$oldIFS
-            echo "$d/$2"
-            return 0
-        fi
-    done
-    IFS=$oldIFS
-    echo ""
-    return 1
+   case "$1" in
+   */*)
+      if [ -x "$1" ] ; then
+         echo "$1"
+         return 0
+      fi
+      ;;
+   esac
+
+   oldIFS=$IFS
+   IFS=':'
+   for d in $PATH
+   do
+      # echo "testing: $d/$1" 1>&2
+      if [ -x "$d/$1" -a ! -d "$d/$1" ] ; then
+         # echo "Found exec: $d/$1" 1>&2
+         IFS=$oldIFS
+         echo "$d/$1"
+         return 0
+      fi
+   done
+   IFS=$oldIFS
+   echo ""
+   return 1
 }
 
-fullPath () {
-if [ `dirname $1 | cut -c1` = "/" ] ; then
-    echo "$1"
-else
-    echo "`pwd`/$1"
-fi
-}
-
+# grep for $1
 getPID() {
-    ps -u $LOGNAME -o 'pid,args' | fgrep "$1 " | fgrep -v grep | head -1 | awk '{ print $1 }'
+   ps -u $LOGNAME -o 'pid,args' | fgrep "$1 " | fgrep -v grep | head -1 | awk '{ print $1 }'
 }
 
-expenv () {
-    eval "echo $1"
-}
 
-nwords () {
-    echo $#
-}
-
-consultGuide () {
+consultGuide() {
 cat<<EOF
 
 Please consult the User Guide for details of parallel running
@@ -96,148 +96,161 @@ EOF
 
 # MAIN SCRIPT
 #~~~~~~~~~~~~
-SCREEN="no"
-PARALLEL="no"
+SCREEN=no
+PARALLEL=no
 
-OPTS=`getopt sph $*`
-if [ $? -ne 0 ] ; then
-    echo "Aborting due to invalid option"
-    printUsage
-    exit 1
-fi
-eval set -- "$OPTS"
-while [ $1 != -- ]; do
-    case $1 in
-        -s) SCREEN="yes";;
-        -p) PARALLEL="yes";;
-        -h) printUsage; exit 1;;
-    esac
-    shift
+
+# parse options
+while [ "$#" -gt 0 ]
+do
+   case "$1" in
+   -h | -help)
+      usage
+      ;;
+   -case)
+      shift
+      caseDir=$1
+      [ "$#" -ge 1 ] || usage "'-case' option requires an argument"
+      cd "$caseDir" 2>/dev/null || usage "directory does not exist:  '$caseDir'"
+      ;;
+   -s)
+      SCREEN=yes
+      shift
+      ;;
+   -p)
+      PARALLEL=yes
+      shift
+      ;;
+   -v)
+      shift
+      version=$1
+      shift
+      ;;
+   --)
+      shift
+      break
+      ;;
+   -*)
+      usage "invalid option '$1'"
+      ;;
+   *)
+      break
+      ;;
+   esac
 done
-shift
 
-if [ $1 ] ; then
-    APPLICATION=`findExec "$PATH" $1`
-    if [ $? -ne 0 ] ; then
-        echo "Application '$1' executable not found.  Exiting..."
-        echo ''
-        printUsage
-        exit 1
-    else
-        echo "Application : $1"
-    fi
-else
-    echo 'No application specified.  Exiting...'
-    echo ''
-    printUsage
-    exit 1
-fi    
-shift
-
-if [ $1 ] ; then
-    if [ -d $1 ] ; then
-        echo "Root        : $1"
-        ROOT=`fullPath $1`
-    else
-        echo "Directory '$1' does not exist.  Exiting..."
-        echo ''
-        printUsage
-    exit 1
-    fi
-else
-    echo 'No root directory specified.  Exiting...'
-    echo ''
-    printUsage
-    exit 1    
+if [ "$#" -lt 1 ]; then
+   usage "No application specified"
 fi
-shift
 
-if [ $1 ] ; then
-    if [ -d ${ROOT}/$1 ] ; then
-        echo "Case        : $1"
-        CASE=$1
-    else
-        echo "Case directory '$1' does not exist.  Exiting..."
-        echo ''
-        printUsage
-        exit 1
-    fi
+# use foamExec for a specified version and for remote (parallel) runs
+if [ -n "$version" -o "$PARALLEL" = yes ]; then
+   APPLICATION=`findExec foamExec`
+   if [ $? -ne 0 ]; then
+      usage "'foamExec' not found"
+   fi
+   if [ -n "$version" ]; then
+      APPLICATION="$APPLICATION -v $version"
+   fi
 else
-    echo 'No case directory specified.  Exiting...'
-    echo ''
-    printUsage
-    exit 1    
+   APPLICATION=`findExec $1`
+   if [ $? -ne 0 ]; then
+      usage "Application '$1' executable not found"
+   fi
+   echo "Application : $1"
+   shift
 fi
-shift
 
-echo ""
-
-if [ "$PARALLEL" = "no" ] ; then
+if [ "$PARALLEL" = no ]; then
 #
 #   RUN ON SINGLE PROCESSOR
 #
-    if [ "$SCREEN" = "no" ] ; then
-        echo "Executing: $APPLICATION $ROOT $CASE > ${ROOT}/${CASE}/log &"
-        $APPLICATION $ROOT $CASE > ${ROOT}/${CASE}/log &
+    if [ "$SCREEN" = no ]; then
+       echo "Executing: $APPLICATION $@ > log 2>&1 &"
+       $APPLICATION $@ > log 2>&1 &
     else
-        echo "Executing: $APPLICATION $ROOT $CASE | tee ${ROOT}/${CASE}/log"
-        $APPLICATION $ROOT $CASE | tee ${ROOT}/${CASE}/log &
-        wait $!
+       echo "Executing: $APPLICATION $@ | tee log &"
+       $APPLICATION $@ | tee log &
+       wait $!
     fi
 else
+
 #
-#   IS THE CASE DECOMPOSED?   
+#   IS THE CASE DECOMPOSED?
 #
-    if [ -r "${ROOT}/${CASE}/processor0" ] ; then
-        PROCS="`ls -d ${ROOT}/${CASE}/processor*`"
-        NPROCS=`nwords $PROCS`
-        echo "Case is decomposed into $NPROCS processors"
-    else
-        echo "Case is not currently decomposed"
-        if [ -r ${ROOT}/${CASE}/system/decomposeParDict ] ; then
-            echo "${CASE}/system/decomposeParDict exists"
-            echo "Try decomposing with \"foamJob decomposePar ${ROOT} ${CASE}\""
-            exit 1
-        else
-            echo "Cannot find ${CASE}/system/decomposeParDict file required to decompose the case for parallel running."
-            consultGuide
-            exit 1
-        fi       
-    fi
+   if [ -r "processor0" ] ; then
+      NPROCS="`/bin/ls -1d processor* | wc -l`"
+   else
+      echo "Case is not currently decomposed"
+      if [ -r system/decomposeParDict ] ; then
+         echo "system/decomposeParDict exists"
+         echo "Try decomposing with \"foamJob decomposePar\""
+         exit 1
+      else
+         echo "Cannot find system/decomposeParDict file required to decompose the case for parallel running."
+         consultGuide
+         exit 1
+      fi
+   fi
+#
+#   LOCATE MPIRUN
+#
+   mpirun=`findExec mpirun`
+   if [ $? -ne 0 ]; then
+      usage "'mpirun' not found"
+   fi
+   mpiopts="-np $NPROCS"
+
 #
 #   IS THE MACHINE READY TO RUN PARALLEL?
 #
-    echo "Parallel processing uses $WM_MPLIB"
-    if [ "$WM_MPLIB" = "LAM" ] ; then
-        LAM_PID=`getPID lamd`
-        if [ ! "$LAM_PID" ] ; then
-            echo "No LAM daemon running."
-            if [ -r ${ROOT}/${CASE}/system/machines ] ; then
-                echo "${CASE}/system/machines file exists"
-                echo "Try starting the LAM multicomputer with \"lamboot -v ${ROOT}/${CASE}/system/machines\""
-                exit 1
-            else
-                echo "Cannot find a 'machines' file for LAM in ${CASE}/system"
-                echo "required to start a LAM multicomputer"
-                consultGuide
-                exit 1
-            fi
-        else
-            echo "LAM daemon running (PID $LAM_PID).  Proceeding with MPI run."
-        fi
-    fi
+   echo "Parallel processing using $WM_MPLIB with $NPROCS processors"
+   case "$WM_MPLIB" in
+   LAM)
+      lamPid=`getPID lamd`
+      if [ ! "$lamPid" ] ; then
+         echo "No LAM daemon running."
+         if [ -r system/machines ] ; then
+            echo "system/machines file exists"
+            echo "Try starting the LAM multicomputer with \"lamboot -v system/machines\""
+            exit 1
+         else
+            echo "Cannot find a 'machines' file for LAM in system/"
+            echo "required to start a LAM multicomputer"
+            consultGuide
+            exit 1
+         fi
+      else
+         echo "LAM daemon running (PID $lamPid).  Proceeding with MPI run."
+      fi
+      ;;
+   OPENMPI)
+      # add hostfile info
+      for hostfile in \
+         hostfile \
+         machines \
+         system/hostfile \
+         system/machines \
+      ;
+      do
+         if [ -r $hostfile ]; then
+            mpiopts="$mpiopts -hostfile $hostfile"
+            break
+         fi
+      done
+      ;;
+   esac
+
 #
 #   RUN IN PARALLEL
 #
-    if [ "$SCREEN" = "no" ] ; then
-        echo "Executing: mpirun -np $NPROCS $APPLICATION $ROOT $CASE -parallel > ${ROOT}/${CASE}/log 2>&1"
-        mpirun -np $NPROCS $APPLICATION $ROOT $CASE -parallel \
-            > ${ROOT}/${CASE}/log 2>&1 &
-    else
-        echo "Executing: mpirun -np $NPROCS $APPLICATION $ROOT $CASE -parallel | tee ${ROOT}/${CASE}/log"
-        mpirun -np $NPROCS $APPLICATION $ROOT $CASE -parallel \
-            | tee ${ROOT}/${CASE}/log
-    fi
+   if [ "$SCREEN" = no ] ; then
+      echo "Executing: mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1"
+      $mpirun $mpiopts $APPLICATION $@ -parallel > log 2>&1 &
+   else
+      echo "Executing: mpirun $mpiopts $APPLICATION $@ -parallel | tee log"
+      $mpirun $mpiopts $APPLICATION $@ -parallel  | tee log
+   fi
 fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPack b/bin/foamPack
--- a/bin/foamPack
+++ b/bin/foamPack
@@ -5,7 +5,7 @@
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright held by original author
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -24,48 +24,57 @@
 #     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Script
-#     foamPack
+#     foamPack [outputDir]
 #
 # Description
-#     Packs and compresses the foam directory for release
+#     Packs and compresses the OpenFOAM directory for release
 #
 #------------------------------------------------------------------------------
+tmpFile=${TMPDIR:-/tmp}/foamPackFiles.$$
 
-foam=$WM_PROJECT-$WM_PROJECT_VERSION
-timeStamp=`date +%d_%m_%y`
-foamPackFile=$foam'_'${timeStamp}.tgz
+timeStamp=$(date +%Y-%m-%d)
+packDir=$WM_PROJECT-$WM_PROJECT_VERSION
+packFile=${packDir}_${timeStamp}.tgz
 
-echo Packing foam version $foam into $foamPackFile
-echo
-
-if [ ! -d $foam ]
+if [ ! -d $packDir ]
 then
-    echo directory $foam does not exist, exiting !
-    exit 1
+   echo "Error: directory $packDir does not exist"
+   exit 1
 fi
 
-if [ -f $foamPackFile ]
-then
-    echo $foamPackFile already exists,  exiting !
-    exit 1
+# add optional output directory
+if [ -d "$1" ]; then
+   packFile="$1/$packFile"
 fi
 
+if [ -f $packFile ]
+then
+   echo "Error: $packFile already exists"
+   exit 1
+fi
 
 # Create time stamp file
 # ~~~~~~~~~~~~~~~~~~~~~~
 
-echo $timeStamp > $foam/.timeStamp
+echo $timeStamp 2>/dev/null > $packDir/.timeStamp
+
+# Clean up on termination and on Ctrl-C
+trap 'rm -f $tmpFile 2>/dev/null; exit 0' EXIT TERM INT
 
 
-# Pack and compress the foamPackFile using GNU tar
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+# Pack and compress the packFile using GNU tar
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-echo finding and packing
+echo
+echo "Packing foam version $packDir into $packFile"
+echo
+echo "finding and packing"
 
-find $foam                     \
+find -H $packDir               \
     ! -type d -type f          \
     ! -name "*~"               \
  -a ! -name ".*~"              \
+ -a ! -name "*.orig"           \
  -a ! -name "*.dep"            \
  -a ! -name "*.o"              \
  -a ! -name "*.so"             \
@@ -76,26 +85,26 @@ find $foam                     \
  -a ! -name "log[0-9]*"        \
  -a ! -name "so_locations"     \
 | sed                          \
- -e "/$foam\/lib\//d"          \
- -e "/$foam\/src\/mico-[0-9.]*\/platforms/d" \
- -e "/$foam\/src\/mpich-[0-9.]*\/platforms/d" \
- -e "/$foam\/src\/mpich-[0-9.]*\/lib/d" \
- -e "/$foam\/src\/lam-[0-9.]*\/platforms/d" \
- -e '/applications\/bin\//d'   \
- -e '/Make\/[^of]/d'           \
- -e '/Make.[A-Za-z]*\/[^of]/d' \
- -e '/doc\/doxygen\/html/d'    \
- -e '/doc\/doxygen\/latex/d'   \
- -e '/doc\/doxygen\/man/d'     \
- -e '/\/lnInclude/d'           \
- -e '/\/ii_files/d'            \
- > foamFiles.$$
+ -e "\@$packDir/.git/@d"       \
+ -e "\@$packDir/lib/@d"        \
+ -e '\@applications/bin/@d'       \
+ -e '\@/t/@d'                     \
+ -e '\@Make[.A-Za-z]*/[^/]*/@d'   \
+ -e '\@doc/[Dd]oxygen/html@d'     \
+ -e '\@doc/[Dd]oxygen/latex@d'    \
+ -e '\@doc/[Dd]oxygen/man@d'      \
+ -e '\@/lnInclude@d'              \
+ -e '\@/ii_files@d'               \
+ | tee $tmpFile
 
-tar czpf $foamPackFile --files-from foamFiles.$$
+tar czpf $packFile --files-from $tmpFile
 
-rm foamFiles.$$
-
-echo Finished packing and compressing  $foam into file $foamPackFile
-
+if [ $? = 0 ]
+then
+   echo "Finished packing and compressing $packDir into file $packFile"
+else
+   echo "Error: failure packing $packDir into file $packFile"
+   rm -f $packFile 2>/dev/null
+fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackBin b/bin/foamPackBin
--- a/bin/foamPackBin
+++ b/bin/foamPackBin
@@ -5,7 +5,7 @@
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright held by original author
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -24,89 +24,73 @@
 #     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Script
-#     foamPackBin
+#     foamPackBin <arch> [outputDir]
 #
 # Description
-#     Packs and compresses binary version of foam for release
+#     Packs and compresses binary version of OpenFOAM for release
 #
 #------------------------------------------------------------------------------
 
 if [ $# = 0 ]
 then
-   echo foamPackBin : binary type expected, exiting !
+   echo "Error: architecture type expected, exiting"
+   echo
+   echo "Usage : ${0##*/} <arch> [outputDir]"
+   echo
+   exit 1
+fi
+arch=$1
+
+timeStamp=$(date +%Y-%m-%d)
+packDir=$WM_PROJECT-$WM_PROJECT_VERSION
+packFile=${packDir}.${arch}_${timeStamp}.tgz
+
+# add optional output directory
+if [ -d "$2" ]
+then
+   packFile="$2/$packFile"
+fi
+
+if [ -f $packFile ]
+then
+   echo "Error: $packFile already exists"
    exit 1
 fi
 
-bin=$1
-foam=$WM_PROJECT-${WM_PROJECT_VERSION}
-foamPackFile=$foam.$bin'_'`date +%d_%m_%y`.tgz
-mpich=`echo $WM_OPTIONS | sed 's/.*MPICH.*/yes/'`
+# check for essential directories
+for dir in $packDir $packDir/lib/$arch $packDir/applications/bin/$arch
+do
+   if [ ! -d $dir ]
+   then
+      echo "Error: directory $dir does not exist"
+      exit 1
+   fi
+done
 
-if [ ! -d $foam ]
-then
-    echo directory $foam does not exist, exiting !
-    exit 1
-fi
+# get list of directories
+dirList=$(
+   for dir in \
+      $packDir/lib/$arch \
+      $packDir/applications/bin/$arch \
+      $packDir/wmake/rules \
+      ;
+   do
+      [ -d $dir ] && echo $dir
+   done
+)
 
-if [ ! -d $foam/lib/$bin ]
-then
-    echo directory $foam/lib/$bin does not exist, exiting !
-    exit 1
-fi
-
-if [ ! -d $foam/applications/bin/$bin ]
-then
-    echo directory $foam/applications/bin/$bin does not exist, exiting !
-    exit 1
-fi
-
-if [ -f $foamPackFile ]
-then
-    echo $foamPackFile already exists,  exiting !
-    exit 1
-fi
-
-echo Packing $bin port of foam version $foam into $foamPackFile
+echo
+echo "Packing $arch port of $packDir into $packFile"
 echo
 
-packDirs="$foam/lib/$bin $foam/applications/bin/$bin $foam/wmake/rules"
-
-if [ -r $foam/src/mico-[0-9.]*/platforms/$bin ]
-then
-    micoDir=$foam/src/mico-[0-9.]*/platforms/$bin
-else
-    micoDir=""
-fi
-
-if [ -r $foam/src/mpich-[0-9.]*/platforms/$bin ]
-then
-    mpichDir=$foam/src/mpich-[0-9.]*/platforms/$bin
-else
-    mpichDir=""
-fi
-
-if [ -r $foam/src/lam-[0-9.]*/platforms/$bin ]
-then
-    lamDir=$foam/src/lam-[0-9.]*/platforms/$bin
-else
-    lamDir=""
-fi
-
-if [ -r $foam/src/openmpi-[0-9.ab]*/platforms/$bin ]
-then
-    openmpiDir=$foam/src/openmpi-[0-9.ab]*/platforms/$bin
-else
-    openmpiDir=""
-fi
-
-tar czpf $foamPackFile $packDirs $micoDir $mpichDir $lamDir $openmpiDir
+tar czpf $packFile $dirList
 
 if [ $? = 0 ]
 then
-    echo Finished packing and compressing file $foamPackFile
+   echo "Finished packing and compressing file $packFile"
 else
-    echo Failed to pack $foamPackFile. Exiting!
-    rm -f $foamPackFile
+   echo "Error: failure packing $packFile"
+   rm -f $packFile 2>/dev/null
 fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackBinAll b/bin/foamPackBinAll
--- a/bin/foamPackBinAll
+++ b/bin/foamPackBinAll
@@ -1,11 +1,11 @@
-#!/bin/csh -f
+#!/bin/sh
 #------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright held by original author
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -24,22 +24,23 @@
 #     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Script
-#     foamPackBinAll
+#     foamPackBinAll [outputDir]
 #
 # Description
 #     Packs and compresses all binary version of foam for release
 #
 #------------------------------------------------------------------------------
+packDir=$WM_PROJECT-$WM_PROJECT_VERSION
 
-set foam = $WM_PROJECT-$WM_PROJECT_VERSION
+if [ ! -d $packDir ]
+then
+   echo "Error: directory $packDir does not exist"
+   exit 1
+fi
 
-if ( ! -d $foam ) then
-    echo directory $foam does not exist, exiting !
-    exit 1
-endif
-
-foreach bin ($foam/lib/*)
-    foamPackBin $bin:t
-end
+for bin in $packDir/lib/*
+do
+   foamPackBin ${bin##*/} $@
+done
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackGeneral b/bin/foamPackGeneral
--- a/bin/foamPackGeneral
+++ b/bin/foamPackGeneral
@@ -5,7 +5,7 @@
 #  \\    /   O peration     |
 #   \\  /    A nd           | Copyright held by original author
 #    \\/     M anipulation  |
-#------------------------------------------------------------------------------
+#-------------------------------------------------------------------------------
 # License
 #     This file is part of OpenFOAM.
 #
@@ -24,46 +24,47 @@
 #     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Script
-#     foamPackGeneral
+#     foamPackGeneral [outputDir]
 #
 # Description
-#     Packs and compresses the foam directory for release
+#     Packs and compresses the OpenFOAM directory for release
 #
 #------------------------------------------------------------------------------
 
-foam=$WM_PROJECT-$WM_PROJECT_VERSION
-timeStamp=`date +%d_%m_%y`
-foamPackFile=${foam}.General'_'${timeStamp}.tgz
+timeStamp=$(date +%Y-%m-%d)
+packDir=$WM_PROJECT-$WM_PROJECT_VERSION
+packFile=${packDir}.General_${timeStamp}.tgz
 
-echo Packing foam version $foam into $foamPackFile
-echo
-
-if [ ! -d $foam ]
+if [ ! -d $packDir ]
 then
-    echo directory $foam does not exist, exiting !
-    exit 1
+   echo "Error: directory $packDir does not exist"
+   exit 1
 fi
 
-if [ -f $foamPackFile ]
+# add optional output directory
+if [ -d "$1" ]
 then
-    echo $foamPackFile already exists,  exiting !
-    exit 1
+   packFile="$1/$packFile"
 fi
 
+if [ -f $packFile ]
+then
+   echo "Error: $packFile already exists"
+   exit 1
+fi
 
 # Create time stamp file
 # ~~~~~~~~~~~~~~~~~~~~~~
 
-echo $timeStamp > $foam/.timeStamp
+echo $timeStamp 2>/dev/null > $packDir/.timeStamp
 
+# Pack and compress the packFile
+# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
-# Pack and compress the foamPackFile
-# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+echo
+echo "Packing $packDir into $packFile"
+echo
 
-echo finding and packing
-
-foamPackSource $foam $foamPackFile
-
-echo Finished packing and compressing  $foam into file $foamPackFile
+foamPackSource $packDir $packFile
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackSource b/bin/foamPackSource
--- a/bin/foamPackSource
+++ b/bin/foamPackSource
@@ -24,41 +24,47 @@
 #     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 #
 # Script
-#     foamPackSource
+#     foamPackSource <directory> <tarFile>
 #
 # Description
 #     Packs and compresses the .C and .H files and Make/options
 #     and Make/files in a given directory.
 #
 #------------------------------------------------------------------------------
-
-# Default value for TMPDIR
-TMPDIR=${TMPDIR:-/tmp}
+tmpFile=${TMPDIR:-/tmp}/foamPackFiles.$$
 
 if [ $# -ne 2 ]; then
-    echo "Usage : `basename $0` directory tarFile"
-    echo ""
-    echo "Packs all .C and .H files and Make/options and Make/files into"
-    echo "<tarFile>"
-    echo ""
-    exit
+   echo "Usage : ${0##*/} directory tarFile"
+   echo ""
+   echo "Packs all .C and .H files and Make/options and Make/files into"
+   echo "<tarFile>"
+   echo ""
+   exit 1
 fi
 
-if [ ! -d $1 ]; then
-    echo "No directory $1"
-    exit 1
+# canonical form (no double and no trailing dashes)
+packDir=$(echo "$1" | sed -e 's@//*@/@g' -e 's@/$@@')
+packFile=$2
+
+if [ ! -d $packDir ]; then
+   echo "Error: directory $packDir does not exist"
+   exit 1
 fi
 
-if [ -f $2 ]; then
-    echo "$2 already exists."
-    exit 1
+if [ -f $packFile ]; then
+   echo "Error: $packFile already exists"
+   exit 1
 fi
 
-find $1                        \
+# Clean up on termination and on Ctrl-C
+trap 'rm -f $tmpFile 2>/dev/null; exit 0' EXIT TERM INT
+
+find -H $packDir               \
     ! -type d                  \
    \( -type f -o -type l \)    \
     ! -name "*~"               \
  -a ! -name ".*~"              \
+ -a ! -name "*.orig"           \
  -a ! -name "*.dep"            \
  -a ! -name "*.o"              \
  -a ! -name "*.so"             \
@@ -67,18 +73,25 @@ find $1                        \
  -a ! -name "core"             \
  -a ! -name "core.[1-9]*"      \
  -a ! -name "log[0-9]*"        \
+ -a ! -name "libccmio*"        \
+ -a ! -name "\.ebrowse"        \
 | sed                          \
- -e "/$1\/lib\//d"          \
- -e "/$1\/src\/mico-[0-9.]*\/platforms/d" \
- -e "/$1\/src\/mpich-[0-9.]*\/platforms/d" \
- -e "/$1\/src\/mpich-[0-9.]*\/lib/d" \
- -e "/$1\/src\/lam-[0-9.]*\/platforms/d" \
- -e '/applications\/bin\//d'   \
- -e '/Make[.A-Za-z]*\/[^\/]*\//d'    \
- > $TMPDIR/foamFiles.$$
+ -e "\@$packDir/.git/@d"       \
+ -e "\@$packDir/lib/@d"        \
+ -e '\@applications/bin/@d'    \
+ -e '\@/t/@d'                  \
+ -e '\@/Make[.A-Za-z]*/[^/]*/@d'\
+ -e '\@/platforms/@d'          \
+ > $tmpFile
 
-tar czpf $2 --files-from $TMPDIR/foamFiles.$$
+tar czpf $packFile --files-from $tmpFile
 
-rm $TMPDIR/foamFiles.$$
+if [ $? = 0 ]
+then
+   echo "Finished packing and compressing $packDir into file $packFile"
+else
+   echo "Error: failure packing $packDir into file $packFile"
+   rm -f $packFile 2>/dev/null
+fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/paraFoam b/bin/paraFoam
--- a/bin/paraFoam
+++ b/bin/paraFoam
@@ -27,52 +27,78 @@
 #     paraFoam
 #
 # Description
+#     start paraview with the OpenFOAM libraries
 #
 #------------------------------------------------------------------------------
 Script=${0##*/}
-rootDir=${1:-.}                # treat missing root as "."
-caseName=${2:-.}               # treat missing case as "."
-caseDir="$rootDir/$caseName"
 
 usage() {
-    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
-    cat<<USAGE
+   while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+   cat<<USAGE
 
-usage: $Script <root> <case>
-       $Script <case>
-       $Script
+usage: $Script [-case dir]
+
+* start paraview $ParaView_VERSION with the OpenFOAM libraries
 
 USAGE
-    exit 1
+   exit 1
 }
 
-# provide usage
-[ "$1" = "-h" ] && usage
+# parse options
+if [ "$#" -gt 0 ]; then
+   case "$1" in
+   -h | -help)
+      usage
+      ;;
+   -case)
+      shift
+      caseDir=$1
+      [ "$#" -ge 1 ] || usage "'-case' option requires an argument"
+      cd "$caseDir" 2>/dev/null || usage "directory does not exist:  '$caseDir'"
+      ;;
+   *)
+      usage "unknown option/argument: '$*'"
+      ;;
+   esac
+fi
 
-cd "$caseDir" 2>/dev/null || usage "directory does not exist:  '$caseDir'"
-
-# get a sensible caseName (avoid '.' as a case name)
+# get a sensible caseName
 caseName=${PWD##*/}
 
-# global root
+# parent directory for normal or parallel results
 case "$caseName" in
-    processor*) rootDir=".." ;;
-    *)          rootDir="."  ;;
+   processor*) parentDir=".." ;;
+   *)          parentDir="."  ;;
 esac
 
 # check existence of essential files
 for check in system/controlDict system/fvSchemes system/fvSolution
 do
-    [ -s "$rootDir/$check" ] || usage "file does not exist:  '$check'"
+   [ -s "$parentDir/$check" ] || usage "file does not exist:  '$parentDir/$check'"
 done
 
+#caseFile="$caseName.foam"
+caseFile="$caseName.OpenFOAM"
 
-# since we are now in the cwd, ROOT/CASE is '$PWD'
-sed -e s%ROOT/CASE%$PWD%g \
-    -e s%CASE%$caseName%g $WM_PROJECT_DIR/bin/paraFoam.pvs > paraFoam.pvs
+case "$ParaView_VERSION" in
+2*)
+   # Clean up on termination and on Ctrl-C
+   trap "rm -f paraFoam.pvs $caseFile 2>/dev/null; exit 0" EXIT TERM INT
+   touch $caseFile
 
-touch $caseName.foam
-paraview paraFoam.pvs
-rm paraFoam.pvs $caseName.foam 2>/dev/null
+   # since we are now in the cwd, %CASE% is '$PWD/$caseFile'
+   sed -e s%CASE%$PWD/$caseFile%g \
+       $WM_PROJECT_DIR/bin/paraFoam.pvs > paraFoam.pvs
 
+   paraview paraFoam.pvs
+   ;;
+
+*)
+   # Clean up on termination and on Ctrl-C
+   trap "rm -f $caseFile 2>/dev/null; exit 0" EXIT TERM INT
+   touch $caseFile
+   paraview --data=$caseFile
+   ;;
+
+esac
 #------------------------------------------------------------------------------
