Initial SVN check-in OpenFOAM-1.5-dev
git-svn-id: svn://svn.code.sf.net/p/openfoam-extend/svn/trunk/Core/OpenFOAM-1.5-dev@913 e4e07f05-0c2f-0410-a05a-b8ba57e0c909

diff --git a/wmake/wclean b/wmake/wclean
--- a/wmake/wclean
+++ b/wmake/wclean
@@ -28,85 +28,125 @@
 #
 # Description
 #     Clean up the wmake control directory Make and remove the include
-#     directory generated for libraries.
-#
-#     Usage: 
-#        wclean                         (cleans Make)
-#        wclean lib??                   (cleans Make and lnInclude)
-#
-#        wclean <dir>                   (cleans dir/Make)
-#        wclean exe <dir>               (cleans dir/Make)
-#        wclean lib?? <dir>             (cleans dir/Make and lnInclude)
-#        wclean exe <dir> <MakeDir>     (cleans dir/MakeDir)
-#        wclean lib?? <dir> <MakeDir>   (cleans dir/MakeDir and lnInclude)
+#     directories generated for libraries.
 #
 #------------------------------------------------------------------------------
+Script=${0##*/}
+
+usage() {
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    cat<<USAGE
+usage: $Script [dir]
+       $Script target [dir [MakeDir]]
+
+Clean up the wmake control directory Make and remove the include
+directories generated for libraries.
+
+The targets correspond to a subset of the 'wmake' special targets:
+    all       all subdirectories
+    exe       cleans dir/Make
+    lib       cleans dir/Make and dir/lnInclude
+    libso     cleans dir/Make and dir/lnInclude
+    libo      cleans dir/Make and dir/lnInclude
+
+USAGE
+   exit 1
+}
+
+# provide immediate help
+if [ "$1" = "-h" -o "$1" = "-help" ]
+then
+    usage
+fi
+
 
 #------------------------------------------------------------------------------
 # check arguments and change to the directory in which to run wmake
 #------------------------------------------------------------------------------
 
-makeOption=""
-dir="_"
+unset dir makeOption
+MakeDir=Make
 
 if [ $# -ge 1 ]
 then
-    if [ $1 = "lib" -o $1 = "libso" -o $1 = "libo" -o $1 = "exe" -o $1 = "project" ]
+
+    if [ -d "$1" ]
     then
-        makeOption=$1
-    else
         dir=$1
-    fi
-fi
-
-if [ $# -ge 2 ]
-then
-    dir=$2
-fi
-
-if [ $dir != "_" ]
-then
-    if [ -d $dir ]
-    then
-        cd $dir
     else
-        echo $0: directory $dir does not exist
-        exit 1
+        makeOption=$1
     fi
+
+    if [ $# -ge 2 ]
+    then
+        dir=$2
+    fi
+
+    # alternative name for the Make sub-directory
+    if [ $# -ge 3 ]
+    then
+        MakeDir=$3
+    fi
+
+    if [ "$dir" ]
+    then
+        cd $dir 2>/dev/null || {
+            echo "$Script error: could not change to directory '$dir'" 1>&2
+            exit 1
+        }
+    fi
+
+    # provide some feedback
+    echo "$Script ${dir:-./}"
 fi
 
-if [ $# = 3 ]
+#------------------------------------------------------------------------------
+# Recurse the directories tree
+#------------------------------------------------------------------------------
+
+if [ "$makeOption" = all ]
 then
-	MakeDir=$3
-else
-    MakeDir=Make
+    if [ -e Allclean ]
+    then
+        ./Allclean
+        exit $?
+    elif [ ! -d $MakeDir ]
+    then
+        for dir in `find . \( -type d -a -name Make \) -printf "%h "`
+        do
+            $0 $dir
+        done
+        exit 0
+    fi
+
+    # This is the end of the recursion down the application directories tree
+    # so remove the "all" option so that the call to make builds the application
+    makeOption=
 fi
+
+#------------------------------------------------------------------------------
+# Check the existance of the Make directory
+#------------------------------------------------------------------------------
 
 if [ ! -d $MakeDir ]
 then
-    echo $0: $MakeDir directory does not exist, exiting !
-    exit 0
+    echo "$Script error: '$MakeDir' directory does not exist" 1>&2
+    exit 1
 fi
 
+# -----------------------------------------------------------------------------
 
-#------------------------------------------------------------------------------
-
-rm -rf $MakeDir/$WM_OPTIONS $MakeDir/classes
+rm -rf $MakeDir/$WM_OPTIONS $MakeDir/classes 2>/dev/null
 
 find . -name "*.dep" -exec rm {} \;
 
-if [ "$makeOption" = "lib" -o "$makeOption" = "libso" -o "$makeOption" = "libo" ]
-then
-    if [ -d "lnInclude" ]
-    then
-        rm -rf lnInclude
-    fi
-fi
+case "$makeOption" in
+lib | libso | libo )
+    rm -rf lnInclude 2>/dev/null
+    ;;
+esac
 
-rm -rf ii_files
-rm -rf Templates.DB
-
+rm -rf ii_files Templates.DB 2>/dev/null
 rm -f so_locations
-
 
 #------------------------------------------------------------------------------
diff --git a/wmake/wmakeFilesAndOptions b/wmake/wmakeFilesAndOptions
--- a/wmake/wmakeFilesAndOptions
+++ b/wmake/wmakeFilesAndOptions
@@ -27,42 +27,41 @@
 #     wmakeFilesAndOptions
 #
 # Description
-#     Script to scan the current directory for directories and source files 
+#     Script to scan the current directory for directories and source files
 #     and construct Make/files and Make/options
 #
 #     Usage : wmakeFilesAndOptions
 #
 #------------------------------------------------------------------------------
+Script=${0##*/}
 
-if [ ! "$WM_OPTIONS" ]
+#
+# check environment variables
+#
+for check in WM_OPTIONS WM_LINK_LANGUAGE WM_DIR
+do
+    eval test "\$$check" || {
+        echo "$Script error: environment variable \$$check not set" 1>&2
+        exit 1
+    }
+done
+
+if [ -d Make ]
 then
-    echo 'makeFilesAndOptions : environment variable $WM_OPTIONS not set, exiting !'
+    echo "$Script error: Make directory already exists" 1>&2
     exit 1
-fi
-
-
-if [ ! "$WM_DIR" ]
-then
-    echo 'makeFilesAndOptions : environment variable $WM_DIR not set,'
-    exit 1
-fi
-
-
-if [ ! "$WM_LINK_LANGUAGE" ]
-then
-    echo 'makeFilesAndOptions : environment variable $WM_LINK_LANGUAGE not set,'
-    exit 1
-fi
-
-
-if [ ! -d Make ]
-then
+else
     mkdir Make
 fi
 
+[ -e Make/files ] || {
+    echo "$Script: Creating files"
+    $WM_DIR/scripts/makeFiles
+}
 
-$WM_DIR/scripts/makeFiles
-$WM_DIR/scripts/makeOptions
-
+[ -e Make/options ] || {
+    echo "$Script: Creating options"
+    $WM_DIR/scripts/makeOptions
+}
 
 #------------------------------------------------------------------------------
diff --git a/wmake/wmakeLnInclude b/wmake/wmakeLnInclude
--- a/wmake/wmakeLnInclude
+++ b/wmake/wmakeLnInclude
@@ -27,61 +27,133 @@
 #     wmakeLnInclude
 #
 # Description
-#     Link all the source files in the $1 directory into $1/lnInclude
+#     Link all the source files in the <dir> directory into <dir>/lnInclude
 #
-#     Usage: wmakeLnInclude <directory> <ln options>
+#     Usage: wmakeLnInclude [-f] <dir> [-lnOption]
 #
+#     The desired source files:
+#         *.C *.H *.h *.cpp *.cxx *.hpp *.hxx
+#
+#     Avoid
+#         *.c (C source)
+#         .#* (cvs recovered files)
+#------------------------------------------------------------------------------
+Script=${0##*/}
+
+usage() {
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    cat<<USAGE
+
+usage: $Script [-f] <dir> [-lnOption]
+
+    Link all the source files in the <dir> into <dir>/lnInclude
+    * Use '-f' to force an update when the lnInclude directory already exists.
+
+USAGE
+   exit 1
+}
+
 #------------------------------------------------------------------------------
 
-BASEDIR=""
-LNOPTION="-s"
+# simple option parsing
+unset forceUpdate
+unset findOpt
 
-if [ $# = 1 ]
+# simple parse options
+while [ "$#" -gt 0 ]
+do
+    case "$1" in
+    -h | -help)   # provide immediate help
+        usage
+        ;;
+    -f)
+        shift
+        forceUpdate=1
+        ;;
+    -*)
+        usage "unknown option/argument: '$*'"
+        ;;
+    *)
+        break
+        ;;
+    esac
+done
+
+baseDir=$1
+# convert incorrect path/dir/lnInclude to something sensible
+while [ "${baseDir##*/}" = lnInclude ]
+do
+    baseDir="${baseDir%/*}"
+    if [ "$baseDir" = lnInclude ]
+    then
+        baseDir="."
+    fi
+done
+incDir=$baseDir/lnInclude
+
+
+if [ $# -eq 1 ]
 then
-    BASEDIR=$1
-
-elif [ $# = 2 ]
+    lnOpt="-s"
+elif [ $# -eq 2 ]
 then
-    BASEDIR=$1
-    LNOPTION=$2
-
+    lnOpt="$2"
 else
-    echo $0: wrong number of arguments
-    echo "usage : wmakeLnInclude <dir> [-lnOption]"
-    exit 1
+    usage "ERROR: incorrect number of arguments"
 fi
 
-if [ ! -d $BASEDIR ]
+
+if [ ! -d $baseDir ]
 then
-    echo Base directory $BASEDIR does not exist, exiting.
+    echo "$Script error: base directory $baseDir does not exist" 1>&2
+    exit 2
+fi
+
+if [ -d $incDir ]
+then
+    if [ ! "$forceUpdate" ]
+    then
+       # echo "$Script error: include directory $incDir already exists" 1>&2
+       exit 0
+    fi
+else
+    mkdir $incDir
+fi
+
+if [ ! -d $incDir ]
+then
+    echo "$Script error: failed to create include directory $incDir" 1>&2
     exit 0
 fi
 
-INCDIR=$BASEDIR/lnInclude
-
-if [ -d $INCDIR ]
-then
-    #echo $0: include directory $INCDIR already exists, exiting.
-    exit 0
-fi
-
-mkdir $INCDIR
-
-if [ ! -d $INCDIR ]
-then
-    echo $0: failed to create include directory $INCDIR
-    exit 0
-fi
+cd $incDir || exit 1
 
 
 # Link include files
 # ~~~~~~~~~~~~~~~~~~
+echo "$Script: linking include files to $incDir"
 
-echo $0: linking include files to $INCDIR
-echo
+#
+# remove any broken links first (this helps when file locations have moved)
+#
+find -L . -type l -exec rm \{\} \;
 
-cd $INCDIR
-find .. -name lnInclude -prune -o -name .svn -prune -o \( -name '*.[hcHCx]*' -o -name '*.type' \) -exec ln $LNOPTION {} . \;
-
+#
+# create links, avoid recreating links unless necessary
+#
+find .. $findOpt \
+    \( -name lnInclude -o -name Make -o -name config \) -prune \
+ -o \( -name '*.[CHh]' -o -name '*.[ch]xx' -o -name '*.[ch]pp' -o -name '*.type' \)  \
+ -a ! -name ".#*" \
+ -print | \
+    while read src
+    do
+        link=$(readlink ${src##*/})
+        if [ "$link" != "$src" ]
+        then
+            rm $link 2>/dev/null
+            ln $lnOpt $src .
+        fi
+    done
 
 #------------------------------------------------------------------------------
diff --git a/wmake/wmakeScheduler b/wmake/wmakeScheduler
--- a/wmake/wmakeScheduler
+++ b/wmake/wmakeScheduler
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #------------------------------------------------------------------------------
 # =========                 |
 # \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
@@ -31,11 +31,14 @@
 #     - WM_HOSTS contains a list of hosts and number of concurrent processes
 #     eg,
 #        export WM_HOSTS="hostA:1 hostB:2 hostC:1"
+#     - WM_COLOURS contains a list of colours to cycle through
+#        export WM_COLOURS="black blue green cyan red magenta yellow"
 #
 #     Sources the relevant cshrc/bashrc if not set.
 #
 #     WM_PROJECT_DIR, WM_PROJECT and WM_PROJECT_VERSION will have been set
-#     before calling this routine
+#     before calling this routine.
+#     FOAM_INST_DIR may possibly have been set (to find installation)
 #
 # Usage
 #     wmakeScheduler COMMAND
@@ -43,7 +46,7 @@
 #
 #     wmakeScheduler -count
 #         count the total number of slots available in WM_HOSTS
-#         eg,  WM_NCOMPPROCS=$(wmakeScheduler -count)
+#         eg,  export WM_NCOMPPROCS=$(wmakeScheduler -count)
 #
 #-------------------------------------------------------------------------------
 lockDir=$HOME/.wmakeScheduler
@@ -54,17 +57,18 @@ lockDir=$HOME/.wmakeScheduler
 # count the total number of slots available and exit
 if [ "$1" = "-count" ]
 then
-   expr $(
-      for slotGroup in $WM_HOSTS
-      do
-         n=${slotGroup##*:}
-         if [ "$n" = "${slotGroup%%:*}" ]; then n=1; fi # missing ':'
-         echo "+ ${n:-1}"
-      done)
-   exit 0
+    expr $(
+        for slotGroup in $WM_HOSTS
+        do
+            n=${slotGroup##*:}
+            [ "$n" = "${slotGroup%%:*}" ] && n=1  # missing ':'
+            echo "+ ${n:-1}"
+        done
+    )
+    exit 0
 fi
 
-# where to source OpenFOAM settings in a remote shell
+# where to source WM_PROJECT settings in a remote shell
 # This code tries to figure out which cshrc or bashrc to execute.
 # !! Assumes remote computer running same shell and startup files
 # in same location
@@ -72,90 +76,150 @@ fi
 sourceFoam=false    # fallback command
 case $SHELL in
 */csh | */tcsh )    # [t]csh vs bash|ksh|sh
-   shellRc=cshrc
-   ;;
+    shellRc=cshrc
+    ;;
 *)
-   shellRc=bashrc
-   ;;
+    shellRc=bashrc
+    ;;
 esac
 
-# check ~/.OpenFOAM-VERSION
-# check <site>/etc
-# check <site>/.OpenFOAM-VERSION
-if [ "$WM_PROJECT" ]; then
-
-   : ${FOAM_DOT_DIR:=.$WM_PROJECT-$WM_PROJECT_VERSION}
-
-   for i in \
-      $HOME/$FOAM_DOT_DIR \
-      $WM_PROJECT_DIR/etc \
-      $WM_PROJECT_DIR/$FOAM_DOT_DIR \
-      ;
-   do
-      if [ -f "$i/$shellRc" ]; then
-         sourceFoam="$i/$shellRc"
-         break
-      fi
-   done
+# check ~/.$WM_PROJECT/$WM_PROJECT_VERSION/
+# check ~/.$WM_PROJECT/
+# check <installedProject>/etc/
+if [ "$WM_PROJECT" ]
+then
+    for i in \
+        $HOME/.$WM_PROJECT/$WM_PROJECT_VERSION \
+        $HOME/.$WM_PROJECT \
+        $WM_PROJECT_DIR/etc \
+        ;
+    do
+        if [ -f "$i/$shellRc" ]
+        then
+            sourceFoam="$i/$shellRc"
+            break
+        fi
+    done
 fi
 
 # Construct test string for remote execution.
-# Source OpenFOAM settings if OpenFOAM environment not set.
+# Source WM_PROJECT settings if WM_PROJECT environment not set.
+# attempt to preserve the installation directory 'FOAM_INST_DIR'
 case $sourceFoam in
-   */cshrc)  sourceFoam='if ( ! $?WM_PROJECT ) source '"$sourceFoam";;
-   */bashrc) sourceFoam='[ "$WM_PROJECT" ] || . '"$sourceFoam";;
+*/bashrc)
+    if [ "$FOAM_INST_DIR" ]
+    then
+        sourceFoam='[ "$WM_PROJECT" ] || '"FOAM_INST_DIR=$FOAM_INST_DIR . $sourceFoam"
+    else
+        sourceFoam='[ "$WM_PROJECT" ] || '". $sourceFoam"
+    fi
+    ;;
+
+*/cshrc)
+    # TODO: csh equivalent to bash code (preserving FOAM_INST_DIR)
+    sourceFoam='if ( ! $?WM_PROJECT ) source '"$sourceFoam"
+    ;;
 esac
 
-
-# quote double-quotes
-set -- $(echo $* | sed -e s/\"/\'\"\'/g)
-## set -- $(echo $* | sed -e 's/"/\\"/g')
-
+# quote double-quotes for remote command line
+rcmd=$(echo $* | sed -e s/\"/\'\"\'/g)
 ## the same, without forking (not ksh, maybe not /bin/sh either)
-# set -- $(while [ "$#" -gt 0 ]; do echo "${1//\"/'\"'}"; shift; done)
+# rcmd=$(while [ "$#" -gt 0 ]; do echo "${1//\"/'\"'}"; shift; done)
 
+
+# Convert WM_COLOURS into an array
+declare colourList
+nColours=0
+for col in $WM_COLOURS
+do
+    colourList[$nColours]=$col
+    ((nColours = $nColours + 1))
+done
+
+# Bashism: make pipe fail early.
+# This ensures the return value of the command is returned and not of the
+# colouring pipe etc.
+set -o pipefail
+
+
+#
+# colour output by argument 1
+#
+colourPipe()
+{
+    if [ "$1" ]
+    then
+    (
+        while read line
+        do
+            setterm -foreground $1
+            echo "$line"
+        done
+        setterm -foreground default
+    )
+    else
+        cat
+    fi
+}
+
+
+colourIndex=0
 
 while :
 do
-   # 0.5 sec
-   usleep 500000
+    for slotGroup in $WM_HOSTS
+    do
+        # split 'host:N', but catch 'host:' and 'host' too
+        host=${slotGroup%%:*}
+        n=${slotGroup##*:}
+        [ "$n" = "$host" ] && n=1  # missing ':'
+        : ${n:=1}
 
-   for slotGroup in $WM_HOSTS
-   do
-      # split 'host:N', but catch 'host:' and 'host' too
-      host=${slotGroup%%:*}
-      n=${slotGroup##*:}
-      if [ "$n" = "$host" ]; then n=1; fi # missing ':'
-      : ${n:=1}
-
-      ## echo "** slot=$slot host=$host n=$n"
-
-      i=0
-      while [ "$i" -lt "$n" ]
-      do
-         lock="$host:$i"
-         if [ ! -f "$lockDir/$lock" ]
-         then
-            touch "$lockDir/$lock"
-            #echo "ssh $host cd $PWD && $*"
-            if [ "$host" = "$HOST" ]
+        i=0
+        while [ "$i" -lt "$n" ]
+        do
+            lockFile="$lockDir/$host:$i"
+            if lockfile -r0 "$lockFile" 2>/dev/null
             then
-               $*
-            elif [ -n "$JOB_ID" ]
-            then
-               qrsh -inherit -v PWD $host "$*"
-            else
-               ssh $host "$sourceFoam 2>/dev/null; cd $PWD && $*"
+                if [ "$nColours" -gt 0 ]
+                then
+                    # Set colour
+                    colour="${colourList[$colourIndex]}"
+
+                    if [ "$host" = "$HOST" ]; then
+                        eval $* 2>&1 | colourPipe "$colour"
+                    else
+                        ssh $host "$sourceFoam 2>/dev/null; cd $PWD && $rcmd" 2>&1 | colourPipe "$colour"
+                    fi
+                    retval=$?
+                else
+                    if [ "$host" = "$HOST" ]; then
+                        eval $* 2>&1
+                    else
+                        ssh $host "$sourceFoam 2>/dev/null; cd $PWD && $rcmd" 2>&1
+                    fi
+                    retval=$?
+                fi
+
+                # Release lock
+                rm -f "$lockFile" 2>/dev/null
+                exit $retval
             fi
-            retval=$?
-            ## echo "** Releasing $lock"
-            rm -f "$lockDir/$lock" 2>/dev/null
-            exit $retval
-         fi
-         i=$(expr $i + 1)
-      done
-   done
+            i=$(expr $i + 1)
+
+            # Cycle through colours. Note: outside lock clause!
+            colourIndex=$(expr $colourIndex + 1)
+            [ "$colourIndex" -lt "$nColours" ] || colourIndex=0
+
+        done
+    done
+    # Did not find any free slots. Rest a bit.
+    sleep 1
 done
 
+if [ "$nColours" -gt 0 ]
+then
+    setterm -foreground default
+fi
 
 #------------------------------------------------------------------------------
